name: decadeweb
favicon: null
layout_spectrum: 0.49888
typography_spectrum: 0.63984
title: DecadeWeb
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-34308926-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b20000'
    - '#222222'
    - '#ffffff'
    - '#eeeeee'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
