name: DecadeWeb Resources
favicon: null
layout_spectrum: 0.49888
typography_spectrum: 0.39673
title: DecadeWeb Resources
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-34308926-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b20000'
    - '#222222'
    - '#ffffff'
    - '#eeeeee'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
