name: decadeweb
favicon: null
layout_spectrum: 0.55108
typography_spectrum: 0.83074
title: DecadeWeb
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-34308926-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#260202'
    - '#8b8b8b'
    - '#c9c9c9'
    - '#a70609'
    - '#f61a1a'
  brandStrength: 0.75
  lightness: 0.7075681055430323
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
